#!/bin/bash

echo "All tools you need : "
echo "
   -> 1) glow : Read markdown beautiful in terminal
   -> 2) tldr : Give example for command and explain useful
"
read -p "Enter your choice : " choice
echo -e "----------------------------"

case ${choice,,} in
	1 | glow)
		apt install glow
		;;
	2 | tldr)
		apt install tldr
		;;
	*)
		echo "Choice number or name of application"
esac
